services:
  django:
    build: .
    container_name: django
    command: gunicorn -c wsgi/gunicorn.conf.py askme.wsgi:application
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/src/app/static
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - django

volumes:
  pgdbdata: null