# Generated by Django 5.1.2 on 2024-12-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/no_avatar.png', upload_to='avatar/%y/%m/%d', verbose_name='avatar'),
        ),
    ]
