# Generated by Django 5.1.2 on 2024-12-24 00:44

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
